# Generated by Django 3.0.8 on 2021-05-23 15:54

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('feed', '0003_auto_20210522_1917'),
    ]

    operations = [
        migrations.RenameField(
            model_name='feedlike',
            old_name='feed',
            new_name='post',
        ),
        migrations.AlterUniqueTogether(
            name='feedlike',
            unique_together={('post', 'creator')},
        ),
    ]
