# Generated by Django 3.0.8 on 2021-05-22 18:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('feed', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='feedcomment',
            options={'ordering': ['-created_at']},
        ),
        migrations.AlterModelOptions(
            name='feedpost',
            options={'ordering': ['-created_at']},
        ),
    ]
