# Generated by Django 3.0.8 on 2021-05-22 19:17

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('feed', '0002_auto_20210522_1855'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='feedlike',
            unique_together={('feed', 'creator')},
        ),
    ]
